// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

class JavascriptArray;
class JavascriptMap;
enum class JavascriptType;

class JavascriptObject {
public:
    virtual ~JavascriptObject() {}

    virtual JavascriptType getType() = 0;

    virtual bool isNull() = 0;

    static std::shared_ptr<JavascriptObject> fromNull();

    virtual bool asBoolean() = 0;

    static std::shared_ptr<JavascriptObject> fromBoolean(bool value);

    virtual double asDouble() = 0;

    static std::shared_ptr<JavascriptObject> fromDouble(double value);

    virtual int32_t asInt() = 0;

    static std::shared_ptr<JavascriptObject> fromInt(int32_t value);

    virtual std::string asString() = 0;

    static std::shared_ptr<JavascriptObject> fromString(const std::string & value);

    virtual std::shared_ptr<JavascriptArray> asArray() = 0;

    static std::shared_ptr<JavascriptObject> fromArray(const std::shared_ptr<JavascriptArray> & value);

    virtual std::shared_ptr<JavascriptMap> asMap() = 0;

    static std::shared_ptr<JavascriptObject> fromMap(const std::shared_ptr<JavascriptMap> & value);
};
