// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#pragma once

#include <memory>

class JavascriptArray;
class JavascriptMap;

class ReactBridge {
public:
    virtual ~ReactBridge() {}

    virtual std::shared_ptr<JavascriptMap> createMap() = 0;

    virtual std::shared_ptr<JavascriptArray> createArray() = 0;

    virtual std::shared_ptr<JavascriptMap> copyMap(const std::shared_ptr<JavascriptMap> & map) = 0;

    virtual std::shared_ptr<JavascriptArray> copyArray(const std::shared_ptr<JavascriptArray> & array) = 0;
};
