// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#pragma once

#include <memory>
#include <vector>

class JavascriptObject;

class JavascriptCallback {
public:
    virtual ~JavascriptCallback() {}

    virtual void invoke(const std::vector<std::shared_ptr<JavascriptObject>> & args) = 0;

    virtual void invokeSingleArg(const std::shared_ptr<JavascriptObject> & arg) = 0;
};
