// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

class JavascriptArray;
class JavascriptMapKeyIterator;
class JavascriptObject;
enum class JavascriptType;

class JavascriptMap {
public:
    virtual ~JavascriptMap() {}

    virtual bool hasKey(const std::string & name) = 0;

    virtual bool isNull(const std::string & name) = 0;

    virtual bool getBoolean(const std::string & name) = 0;

    virtual double getDouble(const std::string & name) = 0;

    virtual int32_t getInt(const std::string & name) = 0;

    virtual std::string getString(const std::string & name) = 0;

    virtual std::shared_ptr<JavascriptArray> getArray(const std::string & name) = 0;

    virtual std::shared_ptr<JavascriptMap> getMap(const std::string & name) = 0;

    virtual std::shared_ptr<JavascriptObject> getObject(const std::string & name) = 0;

    virtual JavascriptType getType(const std::string & name) = 0;

    virtual std::shared_ptr<JavascriptMapKeyIterator> keySetIterator() = 0;

    virtual void putNull(const std::string & key) = 0;

    virtual void putBoolean(const std::string & key, bool value) = 0;

    virtual void putDouble(const std::string & key, double value) = 0;

    virtual void putInt(const std::string & key, int32_t value) = 0;

    virtual void putString(const std::string & key, const std::string & value) = 0;

    virtual void putArray(const std::string & key, const std::shared_ptr<JavascriptArray> & value) = 0;

    virtual void putMap(const std::string & key, const std::shared_ptr<JavascriptMap> & value) = 0;

    virtual void putObject(const std::string & key, const std::shared_ptr<JavascriptObject> & value) = 0;

    virtual void merge(const std::shared_ptr<JavascriptMap> & source) = 0;
};
