// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#pragma once

#include <string>

class JavascriptMapKeyIterator {
public:
    virtual ~JavascriptMapKeyIterator() {}

    virtual bool hasNextKey() = 0;

    virtual std::string nextKey() = 0;
};
