// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#pragma once

#include <cstdint>
#include <memory>
#include <string>

class JavascriptMap;
class JavascriptObject;
enum class JavascriptType;

class JavascriptArray {
public:
    virtual ~JavascriptArray() {}

    virtual int32_t size() = 0;

    virtual bool isNull(int32_t index) = 0;

    virtual bool getBoolean(int32_t index) = 0;

    virtual double getDouble(int32_t index) = 0;

    virtual int32_t getInt(int32_t index) = 0;

    virtual std::string getString(int32_t index) = 0;

    virtual std::shared_ptr<JavascriptArray> getArray(int32_t index) = 0;

    virtual std::shared_ptr<JavascriptMap> getMap(int32_t index) = 0;

    virtual std::shared_ptr<JavascriptObject> getObject(int32_t index) = 0;

    virtual JavascriptType getType(int32_t index) = 0;

    virtual void pushNull() = 0;

    virtual void pushBoolean(bool value) = 0;

    virtual void pushDouble(double value) = 0;

    virtual void pushInt(int32_t value) = 0;

    virtual void pushString(const std::string & value) = 0;

    virtual void pushArray(const std::shared_ptr<JavascriptArray> & array) = 0;

    virtual void pushMap(const std::shared_ptr<JavascriptMap> & map) = 0;

    virtual void pushObject(const std::shared_ptr<JavascriptObject> & object) = 0;

    virtual void append(const std::shared_ptr<JavascriptArray> & source) = 0;
};
