// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#pragma once

class JobDispatcher {
public:
    virtual ~JobDispatcher() {}

    virtual void start() = 0;

    virtual void quit() = 0;
};
