// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#include "JavascriptCallback.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol RVJavascriptCallback;

namespace djinni_generated {

class JavascriptCallback
{
public:
    using CppType = std::shared_ptr<::JavascriptCallback>;
    using CppOptType = std::shared_ptr<::JavascriptCallback>;
    using ObjcType = id<RVJavascriptCallback>;

    using Boxed = JavascriptCallback;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

