// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#include "JavascriptMap.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol RVJavascriptMap;

namespace djinni_generated {

class JavascriptMap
{
public:
    using CppType = std::shared_ptr<::JavascriptMap>;
    using CppOptType = std::shared_ptr<::JavascriptMap>;
    using ObjcType = id<RVJavascriptMap>;

    using Boxed = JavascriptMap;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

