// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#import "RVJavascriptType.h"
#import <Foundation/Foundation.h>
@class RVJavascriptObject;
@protocol RVJavascriptArray;
@protocol RVJavascriptMap;


@protocol RVJavascriptArray

- (int32_t)size;

- (BOOL)isNull:(int32_t)index;

- (BOOL)getBoolean:(int32_t)index;

- (double)getDouble:(int32_t)index;

- (int32_t)getInt:(int32_t)index;

- (nonnull NSString *)getString:(int32_t)index;

- (nullable id<RVJavascriptArray>)getArray:(int32_t)index;

- (nullable id<RVJavascriptMap>)getMap:(int32_t)index;

- (nullable RVJavascriptObject *)getObject:(int32_t)index;

- (RVJavascriptType)getType:(int32_t)index;

- (void)pushNull;

- (void)pushBoolean:(BOOL)value;

- (void)pushDouble:(double)value;

- (void)pushInt:(int32_t)value;

- (void)pushString:(nonnull NSString *)value;

- (void)pushArray:(nullable id<RVJavascriptArray>)array;

- (void)pushMap:(nullable id<RVJavascriptMap>)map;

- (void)pushObject:(nullable RVJavascriptObject *)object;

- (void)append:(nullable id<RVJavascriptArray>)source;

@end
