// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#import "RVJavascriptMapKeyIterator+Private.h"
#import "RVJavascriptMapKeyIterator.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class JavascriptMapKeyIterator::ObjcProxy final
: public ::JavascriptMapKeyIterator
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::JavascriptMapKeyIterator;
public:
    using ObjcProxyBase::ObjcProxyBase;
    bool hasNextKey() override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() hasNextKey];
            return ::djinni::Bool::toCpp(objcpp_result_);
        }
    }
    std::string nextKey() override
    {
        @autoreleasepool {
            auto objcpp_result_ = [djinni_private_get_proxied_objc_object() nextKey];
            return ::djinni::String::toCpp(objcpp_result_);
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto JavascriptMapKeyIterator::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto JavascriptMapKeyIterator::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
