// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#import <Foundation/Foundation.h>


@protocol RVJavascriptMapKeyIterator

- (BOOL)hasNextKey;

- (nonnull NSString *)nextKey;

@end
