// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#import <Foundation/Foundation.h>
@class RVJavascriptObject;


@protocol RVJavascriptCallback

- (void)invoke:(nonnull NSArray<RVJavascriptObject *> *)args;

- (void)invokeSingleArg:(nullable RVJavascriptObject *)arg;

@end
