// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#import "RVJavascriptType.h"
#import <Foundation/Foundation.h>
@class RVJavascriptObject;
@protocol RVJavascriptArray;
@protocol RVJavascriptMap;


@interface RVJavascriptObject : NSObject

- (RVJavascriptType)getType;

- (BOOL)isNull;

+ (nullable RVJavascriptObject *)fromNull;

- (BOOL)asBoolean;

+ (nullable RVJavascriptObject *)fromBoolean:(BOOL)value;

- (double)asDouble;

+ (nullable RVJavascriptObject *)fromDouble:(double)value;

- (int32_t)asInt;

+ (nullable RVJavascriptObject *)fromInt:(int32_t)value;

- (nonnull NSString *)asString;

+ (nullable RVJavascriptObject *)fromString:(nonnull NSString *)value;

- (nullable id<RVJavascriptArray>)asArray;

+ (nullable RVJavascriptObject *)fromArray:(nullable id<RVJavascriptArray>)value;

- (nullable id<RVJavascriptMap>)asMap;

+ (nullable RVJavascriptObject *)fromMap:(nullable id<RVJavascriptMap>)value;

@end
