// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#import "RVJavascriptCallback+Private.h"
#import "RVJavascriptCallback.h"
#import "DJIMarshal+Private.h"
#import "DJIObjcWrapperCache+Private.h"
#import "RVJavascriptObject+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class JavascriptCallback::ObjcProxy final
: public ::JavascriptCallback
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::JavascriptCallback;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void invoke(const std::vector<std::shared_ptr<::JavascriptObject>> & c_args) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() invoke:(::djinni::List<::djinni_generated::JavascriptObject>::fromCpp(c_args))];
        }
    }
    void invokeSingleArg(const std::shared_ptr<::JavascriptObject> & c_arg) override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() invokeSingleArg:(::djinni_generated::JavascriptObject::fromCpp(c_arg))];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto JavascriptCallback::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto JavascriptCallback::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
