// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#include "JavascriptArray.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol RVJavascriptArray;

namespace djinni_generated {

class JavascriptArray
{
public:
    using CppType = std::shared_ptr<::JavascriptArray>;
    using CppOptType = std::shared_ptr<::JavascriptArray>;
    using ObjcType = id<RVJavascriptArray>;

    using Boxed = JavascriptArray;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

