// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, RVJavascriptType)
{
    RVJavascriptTypeNIL,
    RVJavascriptTypeBOOLEAN,
    RVJavascriptTypeNUMBER,
    RVJavascriptTypeSTRING,
    RVJavascriptTypeARRAY,
    RVJavascriptTypeMAP,
};
