// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#import <Foundation/Foundation.h>
@class RVJob;


@interface RVJobQueue : NSObject

- (nullable RVJob *)poll;

- (void)interruptPoll;

@end
