// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#include "JobDispatcher.hpp"
#include <memory>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@protocol RVJobDispatcher;

namespace djinni_generated {

class JobDispatcher
{
public:
    using CppType = std::shared_ptr<::JobDispatcher>;
    using CppOptType = std::shared_ptr<::JobDispatcher>;
    using ObjcType = id<RVJobDispatcher>;

    using Boxed = JobDispatcher;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCppOpt(const CppOptType& cpp);
    static ObjcType fromCpp(const CppType& cpp) { return fromCppOpt(cpp); }

private:
    class ObjcProxy;
};

}  // namespace djinni_generated

