// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#import "RVJobDispatcher+Private.h"
#import "RVJobDispatcher.h"
#import "DJIObjcWrapperCache+Private.h"
#include <stdexcept>

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

namespace djinni_generated {

class JobDispatcher::ObjcProxy final
: public ::JobDispatcher
, private ::djinni::ObjcProxyBase<ObjcType>
{
    friend class ::djinni_generated::JobDispatcher;
public:
    using ObjcProxyBase::ObjcProxyBase;
    void start() override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() start];
        }
    }
    void quit() override
    {
        @autoreleasepool {
            [djinni_private_get_proxied_objc_object() quit];
        }
    }
};

}  // namespace djinni_generated

namespace djinni_generated {

auto JobDispatcher::toCpp(ObjcType objc) -> CppType
{
    if (!objc) {
        return nullptr;
    }
    return ::djinni::get_objc_proxy<ObjcProxy>(objc);
}

auto JobDispatcher::fromCppOpt(const CppOptType& cpp) -> ObjcType
{
    if (!cpp) {
        return nil;
    }
    return dynamic_cast<ObjcProxy&>(*cpp).djinni_private_get_proxied_objc_object();
}

}  // namespace djinni_generated
