// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#import <Foundation/Foundation.h>
@class RVJobQueue;
@protocol RVJavascriptArray;
@protocol RVJavascriptMap;
@protocol RVJobDispatcher;


@protocol RVReactBridge

- (nullable id<RVJavascriptMap>)createMap;

- (nullable id<RVJavascriptArray>)createArray;

- (nullable id<RVJavascriptMap>)copyMap:(nullable id<RVJavascriptMap>)map;

- (nullable id<RVJavascriptArray>)copyArray:(nullable id<RVJavascriptArray>)array;

- (void)emitEventWithMap:(nonnull NSString *)name
                  params:(nullable id<RVJavascriptMap>)params;

- (void)emitEventWithArray:(nonnull NSString *)name
                    params:(nullable id<RVJavascriptArray>)params;

- (nullable id<RVJobDispatcher>)createJobDispatcher:(nullable RVJobQueue *)queue;

@end
