// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#pragma once

#include "Job.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeJob final : ::djinni::JniInterface<::Job, NativeJob> {
public:
    using CppType = std::shared_ptr<::Job>;
    using CppOptType = std::shared_ptr<::Job>;
    using JniType = jobject;

    using Boxed = NativeJob;

    ~NativeJob();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeJob>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeJob>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeJob();
    friend ::djinni::JniClass<NativeJob>;
    friend ::djinni::JniInterface<::Job, NativeJob>;

};

}  // namespace djinni_generated
