// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#include "NativeJobDispatcher.hpp"  // my header

namespace djinni_generated {

NativeJobDispatcher::NativeJobDispatcher() : ::djinni::JniInterface<::JobDispatcher, NativeJobDispatcher>() {}

NativeJobDispatcher::~NativeJobDispatcher() = default;

NativeJobDispatcher::JavaProxy::JavaProxy(JniType j) : Handle(::djinni::jniGetThreadEnv(), j) { }

NativeJobDispatcher::JavaProxy::~JavaProxy() = default;

void NativeJobDispatcher::JavaProxy::start() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeJobDispatcher>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_start);
    ::djinni::jniExceptionCheck(jniEnv);
}
void NativeJobDispatcher::JavaProxy::quit() {
    auto jniEnv = ::djinni::jniGetThreadEnv();
    ::djinni::JniLocalScope jscope(jniEnv, 10);
    const auto& data = ::djinni::JniClass<::djinni_generated::NativeJobDispatcher>::get();
    jniEnv->CallVoidMethod(Handle::get().get(), data.method_quit);
    ::djinni::jniExceptionCheck(jniEnv);
}

}  // namespace djinni_generated
