// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#pragma once

#include "JavascriptType.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeJavascriptType final : ::djinni::JniEnum {
public:
    using CppType = ::JavascriptType;
    using JniType = jobject;

    using Boxed = NativeJavascriptType;

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return static_cast<CppType>(::djinni::JniClass<NativeJavascriptType>::get().ordinal(jniEnv, j)); }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, CppType c) { return ::djinni::JniClass<NativeJavascriptType>::get().create(jniEnv, static_cast<jint>(c)); }

private:
    NativeJavascriptType() : JniEnum("com/rushingvise/reactcpp/JavascriptType") {}
    friend ::djinni::JniClass<NativeJavascriptType>;
};

}  // namespace djinni_generated
