// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

#pragma once

#include "JobQueue.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeJobQueue final : ::djinni::JniInterface<::JobQueue, NativeJobQueue> {
public:
    using CppType = std::shared_ptr<::JobQueue>;
    using CppOptType = std::shared_ptr<::JobQueue>;
    using JniType = jobject;

    using Boxed = NativeJobQueue;

    ~NativeJobQueue();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeJobQueue>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeJobQueue>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeJobQueue();
    friend ::djinni::JniClass<NativeJobQueue>;
    friend ::djinni::JniInterface<::JobQueue, NativeJobQueue>;

};

}  // namespace djinni_generated
