// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

package com.rushingvise.reactcpp;

public abstract class JavascriptPromise {
    public abstract void resolveNull();

    public abstract void resolveBoolean(boolean value);

    public abstract void resolveDouble(double value);

    public abstract void resolveInt(int value);

    public abstract void resolveString(String value);

    public abstract void resolveArray(JavascriptArray value);

    public abstract void resolveMap(JavascriptMap value);

    public abstract void resolveObject(JavascriptObject value);

    public abstract void reject(String code, String message);
}
