// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

package com.rushingvise.reactcpp;

public abstract class JavascriptMapKeyIterator {
    public abstract boolean hasNextKey();

    public abstract String nextKey();
}
