// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

package com.rushingvise.reactcpp;

import java.util.ArrayList;

public abstract class JavascriptCallback {
    public abstract void invoke(ArrayList<JavascriptObject> args);

    public abstract void invokeSingleArg(JavascriptObject arg);
}
