// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from react.djinni

package com.rushingvise.reactcpp;

public abstract class JobDispatcher {
    public abstract void start();

    public abstract void quit();
}
