#!/bin/bash
SCRIPT_ROOT="$(dirname $0)"
PROJECT_ROOT="$SCRIPT_ROOT/../../react-native-cpp"
DJINNI_ROOT="$SCRIPT_ROOT/../"
JAVA_PACKAGE=com.rncpp.jni
JAVA_OUTPUT_FOLDER=$PROJECT_ROOT/android/app/src/main/java/com/rncpp/jni
JNI_OUTPUT_FOLDER=$PROJECT_ROOT/android/app/src/main/cpp/gen
CPP_OUTPUT_FOLDER=$PROJECT_ROOT/cpp/gen
OBJC_PREFIX="RC"
OBJC_OUTPUT_FOLDER=$PROJECT_ROOT/ios/rncpp/Generated
OBJC_BRIDGING_HEADER_FILE="rncpp-Bridging-Header.h"
IDL_FILE=main.djinni

set -e

$DJINNI_ROOT/src/run \
   --java-out $JAVA_OUTPUT_FOLDER \
   --java-package $JAVA_PACKAGE \
   --ident-java-field mFooBar \
   --cpp-out $CPP_OUTPUT_FOLDER \
   --jni-out $JNI_OUTPUT_FOLDER \
   --ident-jni-class NativeFooBar \
   --ident-jni-file NativeFooBar \
   --objc-out $OBJC_OUTPUT_FOLDER \
   --objc-type-prefix $OBJC_PREFIX \
   --objcpp-out $OBJC_OUTPUT_FOLDER \
   --idl $IDL_FILE

cd $OBJC_OUTPUT_FOLDER
echo "// AUTOGENERATED!" > $OBJC_BRIDGING_HEADER_FILE
echo "#pragma once" >> $OBJC_BRIDGING_HEADER_FILE
echo >> $OBJC_BRIDGING_HEADER_FILE
for FILE in $(ls -1 $OBJC_PREFIX*.h | grep -v '\+Private\.h'); do
	echo "#import \"$FILE\"" >> $OBJC_BRIDGING_HEADER_FILE
done
cd - >/dev/null
